version: "3"
services:
  exastro-ita:
    container_name: exastro-ita
    hostname: exastro-ita
    privileged: true
    restart: always
    tty: true
    image: exastro/it-automation:1.8.0-ja
    platform: linux/amd64
    ports:
      - "11080:80"
  exastro-oase:
    container_name: exastro-oase
    hostname: exastro-oase
    privileged: true
    restart: always
    tty: true
    build:
      args:
        - OASE_VERSION=1.4.0
      context: ./oase
      dockerfile: Dockerfile
    platform: linux/x86-64
    volumes:
      - ./oase/files/oase_answers.txt:/home/oase/oase_install_package/install_scripts/oase_answers.txt
    #  - ./oase/files/oase_middleware_setup_core.sh:/home/oase/oase_install_package/install_scripts/bin/oase_middleware_setup_core.sh
    #   - ./ita/data/exastro:/exastro
    #   - ./ita/data/var/lib/mysql:/var/lib/mysql
    ports:
      - "12080:80"
  target-web:
    container_name: target-web
    hostname: target-web
    privileged: true
    restart: always
    tty: true
    command: /sbin/init
    build:
      context: ./target-web
      dockerfile: Dockerfile
    platform: linux/x86-64
    ports:
      - "14080:80"
networks:
  default:
      external:
        name: zabbix-docker_zbx_net_frontend
